### ISSUE TITLE
Dialog boxes are not positioned correctly.

### ISSUE THREAD

**Issue by earshinov** [TesterNick/Minesweeper#2]
When constructing dialog boxes, you should pass `parent` to the constructor of `tk.TopLevel` so that the position of the main window is taken into account.

**Comment by TesterNick** [comment]
Fixed in f7a2ca3b03811a2583cd33da31ff1e9ecf82bbf3. I assume you meant `.transient()` method, but I could not make it work on Windows 10. I saw a [topic on StackOverflow](https://stackoverflow.com/questions/44017940/python-2-7-windows-7-tkinter-center-transient-child-window-over-parent). It seems like the method does not work on Windows. So I have chosen another solution. Also I've reduced the maximum number of bombs to 50% of the cells amount.
